import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google"

import Navbar from "./components/Navbar/Navbar";
import { cn } from "@/lib/utils";
import ReduxProvider from "./store/provider";
import connectDB from "./db/mongooseConnect";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //Connect to MongoDB
  connectDB()
  
  return (
    <html lang="en">
      <body className={cn("bg-red-50", fontSans.variable)}>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
