import type { Metadata } from "next";
import "../globals.css";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils";
import Navbar from "../components/Navbar/Navbar";
import Todo from "../components/Todo/Todo";
import Menu from "../components/Todo/Menu";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <div className="flex">
          <Navbar />

            <div className="flex-1 relative...">
              <div className="absolute top-0 right-0 ...">
                <Menu />
              </div>
            </div>

          {children}
        </div>
  );
}
