import type { Metadata } from "next";
import "../globals.css";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils";
import Navbar from "../components/Navbar/Navbar";
import Menu from "../components/Todo/Menu";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <div className="flex">
          <Navbar />
            <div className="grow">
              <div className="grid justify-items-end">
                <Menu />
              </div>
              {children}
            </div>
        </div>
  );
}
